AllCops:
  Include:
    - '**/Capfile'
    - '**/Gemfile'
    - '**/Guardfile'
    - '**/Rakefile'
    - '**/config.ru'
    - '**/Vagrantfile'
  Exclude:
    - 'bundle/**/*'
    - 'db/**/*'
    - 'coverage/**/*'
    - 'log/**/*'
    - 'provision/**/*'
    - 'public/**/*'
    - 'script/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
  DisplayCopNames: true
  TargetRubyVersion: 2.3

ClassAndModuleChildren:
  Enabled: false

ClassLength:
  Enabled: false

Documentation:
  Enabled: false

EmptyLinesAroundClassBody:
  Enabled: false

EmptyLinesAroundModuleBody:
  Enabled: false

PredicateName:
  Enabled: false

LineLength:
  Enabled: false

MethodLength:
  Enabled: false

SpaceBeforeFirstArg:
  Enabled: false

TrailingCommaInArguments:
  EnforcedStyleForMultiline: no_comma

TrailingCommaInLiteral:
  EnforcedStyleForMultiline: no_comma

SpaceInsideHashLiteralBraces:
  EnforcedStyle: space

MultilineOperationIndentation:
  EnforcedStyle: indented

MultilineMethodCallIndentation:
  EnforcedStyle: indented

SignalException:
  EnforcedStyle: semantic

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

PercentLiteralDelimiters:
  PreferredDelimiters:
    '%r': '{}'
    '%i': '[]'
    '%w': '[]'
    '%W': '[]'
    '%Q': '{}'

Rails:
  Enabled: true

Style/Send:
  Enabled: true

Style/UnneededPercentQ:
  Enabled: true

Style/Lambda:
  Enabled: false

Style/ElseAlignment:
  Enabled: false

Lint/EndAlignment:
  AlignWith: variable
